name: "Hub & Spoke Infra"

on:
  push:
    branches:
      - feature/hub-spoke

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform ${{ inputs.terraform_action }}"
    runs-on: ubuntu-latest
    
    environment: poc 

    env:
      ARM_CLIENT_ID: ${{ vars.APP_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.SC_PASSWORD }}
      ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.TENANT_ID }}
      # Variables d'image disponibles pour toutes les steps
      TF_VAR_container_image_name: ${{ inputs.image_name }}
      TF_VAR_container_image_version: ${{ inputs.image_version }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: "Terraform Init"
        id: init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ vars.BACKEND_RG }}" \
            -backend-config="storage_account_name=${{ vars.BACKEND_ST_NAME_DEV }}" \
            -backend-config="container_name=${{ vars.BACKEND_CONTAINER_NAME }}" \
            -backend-config="key=prod.terraform.tfstate"

      - name: "Terraform Validate"
        id: validate
        run: terraform validate

      - name: "Terraform Plan"
        id: plan
        run: |
          terraform plan -out=tfplan